server:
  port: 8082
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: root
  rabbitmq:
    host: 192.168.85.236
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: ly.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1    #保证拿到的是ip地址，而不是localhost
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
